/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.65.2
  Fuel-Core version: 0.37.1
*/

export { FarmContract } from './FarmContract';
export { FarmContractFactory } from './FarmContractFactory';
